config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    get 'about', to: 'static_pages#about'
    devise_for :users

    authenticate :user do
        resources :users do 
            resources :workouts, controller: "users/workouts" do 
                resources :workout_entries, controller: "users/workout_entries" do 
                    post "start" => "workout_entries#start"
                    post "stop" => "workout_entries#stop"
                end
            end
            resources :regiments, controller: "users/regiments"
            resources :exercise_entries, controller: "users/exercise_entries"
        end
    end

    resources :muscles, :exercises, :workouts

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def about 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row bg-secondary justify-content-center align-items-center">
        <div class="col-sm-10 text-center">
            <h1 class="text-capitalize mb-5"><span class="d-block text-warning ">About Kaizen Liftz</span></h1>
            <main class="mb-4">
                <article class="Venn2">
                    <div class="circle one">
                        <span></span>
                        <span></span>
                        <h3 class="text-warning">Kaizen Blitz<span class="text-dark" style="float:none">krieg</span></h3>
                        <br />
                        <p class="text-dark">Loosely translated Japanese “continual improvement” and German “sudden overpowering attack.” Americanized meaning "a sudden overpowering effort to take something apart and put it back together in a better way."</p>
                    </div>
                    <div class="circle two">
                        <span></span>
                        <span></span>
                        <h3 class="text-dark">Weight <span class="text-warning" style="float:none">Lift</span>ing</h3>
                        <p class="text-dark">The activity of lifting heavy bars to strengthen the muscles, either for exercise or in a competition.</p>
                    </div>
                        <div class="shape onetwo">
                        <span></span>
                        <span></span>
                        <h2 class="text-warning">Kaizen Liftz</h2>
                        <p class="text-light">A sudden overpowering effort to continually strengthen the muscles for exercise or competition.</p>
                    </div>
                </article>
            </main>
            <div class="my-5">
                <h1 class="text-capitalize"><span class="d-block text-warning">How to use app</span></h1>
                <p class="text-dark">
                    Add a workout and begin tracking progress made each session. Create and share custom workouts and exercises while targeting specific muscles.
                </p>
            </div>

            <div class="my-5">
                <h1 class="text-capitalize"><span class="d-block text-warning">Why create app</span></h1>
                    As a self-taught developer, I sought to learn and practice the following: Ruby, Rails, OOP, MVC, TDD, Database Design, and Bootstrap.
            </div>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row bg-secondary justify-content-center align-items-center">
        <div class="col-sm-10 text-center">
            <h1 class="display-2 text-capitalize">
                <span class="d-block text-white ">Make Gainz</span>
                <span>
                    <i class="d-block fas fa-dumbbell text-warning fa-1x navbar-brand"> Kaizen Liftz</i>
                </span>
            </h1>
            <%= link_to "Exercises", exercises_path, class:"btn btn-outline-warning btn-lg px-4 m-3" %>
            <%= link_to "Muscles", muscles_path, class:"btn btn-outline-light btn-lg px-4 m-3" %>
            <%= link_to "Workouts", workouts_path, class:"btn btn-outline-dark btn-lg px-4 m-3" %>
        </div>
    </div>
</div>