config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    get 'about', to: 'static_pages#about'
    devise_for :users

    authenticate :user do
        resources :users do 
            resources :workouts, controller: "users/workouts" do 
                resources :workout_entries, controller: "users/workout_entries" do 
                    post "start" => "workout_entries#start"
                    post "stop" => "workout_entries#stop"
                end
            end
            resources :regiments, controller: "users/regiments"
            resources :exercise_entries, controller: "users/exercise_entries"
        end
    end

    resources :muscles, :exercises, :workouts

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :encrypted_password, presence: true, length: { maximum:100, minimum: 6}
  validates :email, presence:true, length: { maximum: 255 }, format:{ with: URI::MailTo::EMAIL_REGEXP}, uniqueness: { case_sensitive: false }
  has_many :workouts

end

app/models/workout.rb
class Workout < ApplicationRecord

  before_save :titleize_name
  validate :has_exercise_requirements    
  validates :name, presence: true, length: { maximum: 100, minimum: 1 }, uniqueness: { case_sensitive: false, scope: :user }
  has_many :regiments, dependent: :destroy
  has_many :exercises, :through => :regiments
  has_many :workout_entries, dependent: :destroy
  belongs_to :user, optional: true
  accepts_nested_attributes_for :regiments, allow_destroy: true

  private 
    def titleize_name
      self.name = name.titleize
    end

    def has_exercise_requirements
      errors.add(:exercise, "is required") unless regiments.map(&:exercise_id).any?
    end

end

app/controllers/users/exercise_entries_controller.rb
module Users 
    class ExerciseEntriesController < ApplicationController
        
        def edit
            @exercise_entry = ExerciseEntry.find(params[:id])
        end

        def update
            @exercise_entry = ExerciseEntry.find(params[:id])
            if @exercise_entry.update_attributes(exercise_params)
                redirect_to user_workout_path(current_user, @exercise_entry.workout_entry.workout)
                else
                    render :edit
                end
        end

        # DESTROY
        def destroy
            @workout = Workout.find(params[:id])
            @workout.destroy
            redirect_to user_workouts_path
        end

        private
            def exercise_params 
                params.require(:exercise_entry).permit(:weight, :sets, :reps, :comments)
            end
    end    
end

app/controllers/users/regiments_controller.rb
module Users
    class RegimentsController < ApplicationController

        # UPDATE
        def edit
            @regiment = Regiment.find(params[:id])
        end

        def update
            @regiment = Regiment.find(params[:id])
            if @regiment.update_attributes(regiment_params)
                redirect_to user_workout_path(current_user, @regiment.workout)
            else
                render :edit
            end
        end

        private
        def regiment_params
            params.require(:regiment).permit(:weight, :sets, :reps)
        end
    end
end

app/controllers/users/workout_entries_controller.rb
module Users 
    class WorkoutEntriesController < ApplicationController

        # READ
        def index
            @user = User.find(params[:user_id])
            @workouts = @user.workouts.order(name: :asc).paginate(page: params[:page], :per_page => 10)
        end

        def show
            @workout = Workout.find(params[:id])
        end

        # CREATE
        def create
            @workout = Workout.find(params[:workout_id])
            new_workout_entry = @workout.workout_entries.create!
            @workout.regiments.each do |regiment|
                new_workout_entry.exercise_entries.create!(exercise: regiment.exercise, sets: regiment.sets, reps: regiment.reps, weight: regiment.weight)
            end
            redirect_to user_workout_path(current_user, @workout)
        end
        
        def new 
            @workout = Workout.find(params[:workout_id])
        end

        # DESTROY
        def destroy
            workout_entry = WorkoutEntry.find(params[:id])
            workout_entry.destroy
            redirect_to user_workout_path(current_user, workout_entry.workout)
        end

    end    
end

app/controllers/users/workouts_controller.rb
module Users
    class WorkoutsController < ApplicationController

        # READ
        def index
            @user = User.find(params[:user_id])
            @workouts = @user.workouts.order(name: :asc).paginate(page: params[:page], :per_page => 10)
        end

        def show
            @workout = Workout.find(params[:id])
            @workout_entries = @workout.workout_entries.order(created_at: :desc) 
        end

        # CREATE
        def create
            workout = Workout.find(params[:workout][:id])
            new_workout = current_user.workouts.build(name: workout.name)
            workout.regiments.each do |regiment|
                new_workout.regiments.build(exercise: regiment.exercise, sets: regiment.sets, reps: regiment.reps, weight: regiment.weight)
            end
            new_workout.save!
            redirect_to workouts_path
        end

        # DESTROY
        def destroy
            Workout.find(params[:id]).destroy
            redirect_to user_workouts_path
        end

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # CREATE
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to(root_path)
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  # UPDATE
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

    private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController\

  before_action :authenticate_user!, except: [:index, :show]

  # READ
  def index
    @workouts = Workout.where(user_id: nil).order(name: :asc).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @workout = Workout.find(params[:id])
  end

  # CREATE
  def new
    @workout = Workout.new
    @workout.regiments.build
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render :new
    end
  end

  # UPDATE
  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update_attributes(workout_params)
      redirect_to @workout
    else
      render :edit
    end
  end

  # DESTROY
  def destroy
    Workout.find(params[:id]).destroy
    redirect_to workouts_url
  end

  private
    def workout_params
      params.require(:workout).permit(:name, :exercise_id, regiments_attributes: [ :id, :exercise_id, :workout_id, :weight, :sets, :reps, :_destroy])
    end

  end
  

app/helpers/users/workout_entries_helper.rb
module Users::WorkoutEntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/users/workouts/_details.html.erb
<div class="card bg-dark text-warning">
    <div class="card-header" id="headingOne">
        <h1 class="mb-0 text-center bg-secondary">
            <button class="btn btn-lg btn-link text-warning" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <%= @workout.name %>
            </button>
        </h1>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionWorkoutEntries">
        <div class="card-body">
            <ul class="list-unstyled my-4 list-inline">
                <div class="row">
                    <li class="text-light list-inline-item col"> Exercise </li>
                    <li class="text-warning list-inline-item col"> Sets </li>
                    <li class="text-warning list-inline-item col"> Reps </li>
                    <li class="text-warning list-inline-item col"> Weight </li>
                    <li class="text-warning list-inline-item col"></li>
                </div>
            </ul>
            <span class="d-block">
                <% @workout.regiments.each do |regiment| %>
                    <ul class="list-unstyled my-4 list-inline">
                        <div class="row">
                            <li class="text-warning list-inline-item col"><%= regiment.exercise.name %></li>
                            <li class="text-light list-inline-item col"> <%= regiment.sets %></li>
                            <li class="text-light list-inline-item col"> <%= regiment.reps %></li>
                            <li class="text-light list-inline-item col"> <%= regiment.weight %></li>
                            <li class="text-light list-inline-item col">
                                <%= link_to 'Edit', edit_user_regiment_path(current_user, regiment),class: "btn btn-outline-warning"%>
                            </li>
                        </div>
                    </ul>
                    <hr >
                <% end %>
            </span>
            <div class="text-center">
                <%= link_to 'Submit Workout Entry', user_workout_workout_entries_path(current_user, @workout), method: :post, class: "btn btn-outline-light"  %>
            </div>
        </div>
    </div>
</div>

app/views/users/workouts/_workout_entry.html.erb
<div class="card-body">
    <span class="text-warning"><%= workout_entry.created_at.strftime("%d %b %Y. %H:%M") %></span>
    <ul class="list-unstyled my-4 list-inline">
        <div class="row">
            <li class="text-light list-inline-item col"> Exercise </li>
            <li class="text-warning list-inline-item col"> Sets </li>
            <li class="text-warning list-inline-item col"> Reps </li>
            <li class="text-warning list-inline-item col"> Weight </li>
            <li class="text-warning list-inline-item col"></li>
        </div>
    </ul>
    <span class="d-block ">
        <% workout_entry.exercise_entries.each do |exercise_entry| %>
            <ul class="list-unstyled my-4 list-inline">
                <div class="row">
                    <li class="text-warning list-inline-item col"><%= exercise_entry.exercise.name %></li>
                    <li class="text-light list-inline-item col"> <%= exercise_entry.sets %></li>
                    <li class="text-light list-inline-item col"> <%= exercise_entry.reps %></li>
                    <li class="text-light list-inline-item col"> <%= exercise_entry.weight %></li>
                    
                    <li class="text-light list-inline-item col">
                        <%= link_to 'Edit', edit_user_exercise_entry_path(current_user, exercise_entry),class: "btn btn-outline-warning" %>
                    </li>
                </div>
                <li class="text-warning list-inline-item pt-4"> Comments: <span class="text-light"><%= exercise_entry.comments %></span></li>
            </ul>
            <hr >
        <% end %>
        <div class="text-center">
            <%= link_to "Delete Workout Entry", user_workout_workout_entry_path(current_user, workout_entry.workout, workout_entry), method: :delete, data: { confirm: "You sure?" }, class: ["btn","btn-danger"] %>
        </div>
    </span>
</div>
    

app/views/users/workouts/edit.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row justify-content-center ">
        <div class="col-sm-10 devise-form rounded bg-dark text-warning">
            <h1 class="text-light">Edit <%= @workout.name %></h1>

            <%= form_for([current_user, @workout]) do |f| %>
            <div class="form-group">
                <%= render 'shared/error_messages', :@profile => @workout %>

                <div class="exercise_set">
                    <div class="exercise_set_item_container my-4" >
                        <%= render 'regiment_fields', f: f, exercises: :exercises %>
                    </div>
                </div>

                <%= link_to 'Back', workouts_path, class: "btn btn-outline-warning" %>
                <%= f.submit "Save", {:class => "btn btn-outline-warning my-2" }%>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/workouts/index.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row justify-content-center ">
        <div class="col-sm-10 devise-form rounded bg-dark text-warning">
            <h1 class="text-center">My Workouts</h1>

            <ul class="list-unstyled bg-secondary rounded list-inline">
                <% @workouts.each do |workout| %>
                    <div class="container">
                        <li class="pt-4 list-inline-item">
                            <%= link_to workout.name, user_workout_path(current_user, workout), {:class => "text-light pl-5 font-weight-bold text-left"} %>
                        </li>
                        
                        <li class="pt-3 list-inline-item float-right">
                            <%= link_to "Remove", user_workout_path(current_user, workout), method: :delete, data: { confirm: "You sure?" }, class: ["btn","btn-danger"] %>
                        </li>
                    </div>
                    <hr>
                <% end %>
            </ul>

            <div class="text-center mt-2">
                <%= link_to 'Home', root_path, class: "btn btn-lg btn-outline-warning"  %>
            </div>
        </div>
    </div>
</div> 

app/views/users/workouts/show.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="col-sm-10 devise-form rounded bg-dark text-warning my-4 container">
        <div class="accordion" id="accordionWorkoutEntries">
            <%= render "details" %>
            <div class="card bg-dark text-light">
                <div class="card-header" id="headingTwo">
                    <h5 class="mb-0 text-center bg-secondary">
                        <button class="btn btn-lg btn-link text-warning collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Workout Entries
                        </button>
                    </h5>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionWorkoutEntries">
                    <div class="card-body">
                        <%= render partial: "workout_entry", collection: @workout_entries %>
                    </div>
                </div>
            </div>
            <div class="text-center mt-5">
                <%= link_to 'Back', user_workouts_path, class: "btn btn-outline-warning"  %>
            </div>
        </div>
    <div>
</div>