config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    get 'about', to: 'static_pages#about'
    devise_for :users

    authenticate :user do
        resources :users do 
            resources :workouts, controller: "users/workouts" do 
                resources :workout_entries, controller: "users/workout_entries" do 
                    post "start" => "workout_entries#start"
                    post "stop" => "workout_entries#stop"
                end
            end
            resources :regiments, controller: "users/regiments"
            resources :exercise_entries, controller: "users/exercise_entries"
        end
    end

    resources :muscles, :exercises, :workouts

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  # READ
  def index
    @exercises = Exercise.order(name: :asc).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  # CREATE
  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save            
      redirect_to @exercise
    else
      render :new
    end
  end

  def new
    @exercise = Exercise.new
    @exercise.intentions.build
  end

  # UPDATE
  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update_attributes(exercise_params)
      redirect_to @exercise
    else
      render :edit
    end
  end

  # DESTROY
  def destroy
    Exercise.find(params[:id]).destroy
    redirect_to exercises_url
  end

private
  def exercise_params
    params.require(:exercise).permit(:name, :comments, intentions_attributes: [ :id, :muscle_id, :primary_muscle, :_destroy])
  end

end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_intention_fields.html.erb
<div class="nested-fields mt-2">
    <%= f.label :muscle_id %>
    <%= f.select :muscle_id, Muscle.all.collect{|muscle|[muscle.name, muscle.id]}, {}, {:class => 'form-control'}%>
    <div class="clearfix mt-2">
        <%= f.check_box :primary_muscle %>
        <%= f.label :primary_muscle %>
        <%= link_to_remove_association 'Remove Muscle', f, class: 'btn btn-danger float-right' %>
    </div>
</div>

app/views/exercises/edit.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row justify-content-center ">
        <div class="col-sm-10 devise-form rounded bg-dark text-warning">
            <h1 class="text-light">Edit <%= @exercise.name%></h1>

            <%= form_for(@exercise) do |f| %>
            <div class="form-group">
                <%= render 'shared/error_messages', :@profile => @exercise %>

                <div class="muscle_set">
                    <div class="muscle_set_item_container my-4" >
                        <%= f.fields_for :intentions do |intention| %>                    
                            <%= render 'intention_fields', f: intention, muscles: :muscles %>
                        <% end %>
                    </div>
                    <%= link_to_add_association 'Add Muscle', f, :intentions, {:class=> "btn btn-outline-warning my-4"}%>
                </div>
                <%= f.label :comments %>
                <%= f.text_field :comments, autofocus: true, class: 'form-control'%>

                <%= link_to 'Back', exercises_path, class: "btn btn-outline-warning" %>
                <%= f.submit "Save", class: "btn btn-outline-warning my-2" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/exercises/index.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row justify-content-center ">
        <div class="col-sm-10 devise-form rounded bg-dark text-warning">
            <h1 class="text-center">Exercises</h1>
            <%= render 'shared/paginate', :@profile => @exercises %>
            <ul class="list-unstyled bg-secondary rounded">
                <% @exercises.each do |exercise| %>
                <li class="m-2 p-1">
                    <%= link_to exercise.name, exercise, {:class => "text-light pl-5 font-weight-bold"}  %>
                </li>
                <hr>
                <% end %>
            </ul>
            <%= render 'shared/paginate', :@profile => @exercises %>
            <div class="text-center mt-2">
                <%= link_to 'Home', root_path, class: "btn btn-lg btn-outline-warning"  %>
                <%= link_to "New Exercise", new_exercise_path, class: "btn btn-lg btn-outline-warning" %>
            </div>
        </div>
    </div>
</div> 

app/views/exercises/new.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row justify-content-center ">
        <div class="col-sm-10 devise-form rounded bg-dark text-warning">
            <h1 class="text-light">New Exercise</h1>

            <%= form_for(@exercise) do |f| %>
            <div class="form-group">
                <%= render 'shared/error_messages', :@profile => @exercise %>
                <%= f.label :name %>
                <%= f.text_field :name, autofocus: true, class: 'form-control'%>

                <div class="muscle_set">
                    <div class="muscle_set_item_container my-4" >
                        <%= f.fields_for :intentions do |intention| %>
                            <%= render 'intention_fields', f: intention, muscles: :muscles %>
                        <% end %>
                    </div>
                    <%= link_to_add_association 'Add Muscle', f, :intentions, {:class=> "btn btn-outline-warning my-4"}%>
                </div>
                
                <%= f.label :comments %>
                <%= f.text_field :comments, autofocus: true, class: 'form-control'%>

                <hr>

                <%= link_to 'Back', exercises_path, class: "btn btn-outline-warning" %>
                <%= f.submit "Save", class: "btn btn-outline-warning my-2" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/exercises/show.html.erb
<div class="container-fluid main pb-5 mb-5">
    <div class="row justify-content-center ">
        <div class="col-sm-10 devise-form rounded bg-dark text-warning pl-5">
            <h1 class="text-center"><%= @exercise.name %></h1>
            
            <div class="d-block mb-2">
                <ul class="text-light list-unstyled list-inline">
                    <div class="my-2">
                        <div class="text-warning"> Primary muscles:</div>
                        <% @exercise.muscle_intentions(:primary).each do |intention| %>
                            <li class="list-inline-item" style="margin-right: -2px">
                            <%= intention.muscle.name %>.
                            </li>
                        <% end %>
                    </div>
                    <div class="my-2">
                        <div class="text-warning"> Secondary muscles:</div>
                            <% @exercise.muscle_intentions(:secondary).each do |intention| %>
                            <li class="list-inline-item" style="margin-right: -2px">
                            <%= intention.muscle.name %>.
                            </li>
                        <% end %>
                    </div>
                </ul>
                <h6 class="text-danger">TODO: Video to come</h6>
                Comments:
                <div class="text-light">
                    <%= @exercise.comments %>
                </div>
            </div>

            <div>
                <%= link_to 'Back', exercises_path, class: "btn btn-outline-warning" %>
                <% if current_user.try(:admin?)%>
                    <a href="/exercises/<%=@exercise.id %>/edit" class="btn btn-outline-warning">
                        Edit
                    </a>
                    <%= link_to "delete", @exercise, method: :delete, data: { confirm: "You sure?" }, class: ["btn","btn-danger"] %> 
                <% end %>
            </div>
        </div>
    </div>
</div>