config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    get 'about', to: 'static_pages#about'
    devise_for :users

    authenticate :user do
        resources :users do 
            resources :workouts, controller: "users/workouts" do 
                resources :workout_entries, controller: "users/workout_entries" do 
                    post "start" => "workout_entries#start"
                    post "stop" => "workout_entries#stop"
                end
            end
            resources :regiments, controller: "users/regiments"
            resources :exercise_entries, controller: "users/exercise_entries"
        end
    end

    resources :muscles, :exercises, :workouts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord

  before_save :titleize_name
  validate :has_muscle_requirements
  validates :name, presence: true, length: { maximum: 100, minimum: 1 }, uniqueness: { case_sensitive: false }
  validates :comments, length: { maximum: 1000 }
  has_many :intentions, dependent: :destroy
  has_many :muscles, :through => :intentions
  has_many :regiments 
  has_many :workouts, :through => :regiments
  accepts_nested_attributes_for :intentions, allow_destroy: true

  def muscle_intentions(intention_type)
    intentions.where(primary_muscle: intention_type == :primary)
  end

  private 
    def titleize_name
      self.name = name.titleize
    end

    def has_muscle_requirements
      errors.add(:muscle, "is required") unless intentions.map(&:muscle_id).any?
      errors.add(:primary_muscle, "is required") unless intentions.any?(&:primary_muscle?)
      if intentions.map(&:muscle_id).uniq != intentions.map(&:muscle_id)
        errors.add(:muscles, "not unique")
      end
  end
end

app/models/exercise_entry.rb
class ExerciseEntry < ApplicationRecord

  validates :weight, numericality: { only_integer: true, less_than_or_equal_to: 1000 }, allow_nil: true
  validates :sets, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100 } 
  validates :reps, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100 } 
  belongs_to :workout_entry
  belongs_to :exercise
  
end

app/models/intention.rb
class Intention < ApplicationRecord
    
  validates :muscle_id, presence: true
  validates :primary_muscle, inclusion: {in: [true, false]}
  belongs_to :exercise
  belongs_to :muscle

end

app/models/muscle.rb
class Muscle < ApplicationRecord

  before_save :titleize_name    
  validates :name, presence: true, length: { maximum: 50, minimum: 2 }, uniqueness: { case_sensitive: false }
  has_many :intentions 
  has_many :exercises, :through => :intentions
    
  private 
    def titleize_name
        self.name = name.titleize
    end
    
end

app/models/regiment.rb
class Regiment < ApplicationRecord

  validates :exercise_id, presence: true
  validates :weight, numericality: { only_integer: true, less_than_or_equal_to: 1000 }, allow_nil: true
  validates :sets, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100 } 
  validates :reps, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100 } 
  belongs_to :exercise
  belongs_to :workout

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :encrypted_password, presence: true, length: { maximum:100, minimum: 6}
  validates :email, presence:true, length: { maximum: 255 }, format:{ with: URI::MailTo::EMAIL_REGEXP}, uniqueness: { case_sensitive: false }
  has_many :workouts

end

app/models/workout.rb
class Workout < ApplicationRecord

  before_save :titleize_name
  validate :has_exercise_requirements    
  validates :name, presence: true, length: { maximum: 100, minimum: 1 }, uniqueness: { case_sensitive: false, scope: :user }
  has_many :regiments, dependent: :destroy
  has_many :exercises, :through => :regiments
  has_many :workout_entries, dependent: :destroy
  belongs_to :user, optional: true
  accepts_nested_attributes_for :regiments, allow_destroy: true

  private 
    def titleize_name
      self.name = name.titleize
    end

    def has_exercise_requirements
      errors.add(:exercise, "is required") unless regiments.map(&:exercise_id).any?
    end

end

app/models/workout_entry.rb
class WorkoutEntry < ApplicationRecord

  validates :workout_id, presence: true
  has_many :exercise_entries, dependent: :destroy
  belongs_to :workout

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  # READ
  def index
    @exercises = Exercise.order(name: :asc).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  # CREATE
  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save            
      redirect_to @exercise
    else
      render :new
    end
  end

  def new
    @exercise = Exercise.new
    @exercise.intentions.build
  end

  # UPDATE
  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    if @exercise.update_attributes(exercise_params)
      redirect_to @exercise
    else
      render :edit
    end
  end

  # DESTROY
  def destroy
    Exercise.find(params[:id]).destroy
    redirect_to exercises_url
  end

private
  def exercise_params
    params.require(:exercise).permit(:name, :comments, intentions_attributes: [ :id, :muscle_id, :primary_muscle, :_destroy])
  end

end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  # READ
  def index
    @muscles = Muscle.order(name: :asc).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @muscle = Muscle.find(params[:id])
  end

  # CREATE
  def create
    @muscle = Muscle.new(muscle_params)
    if @muscle.save
      redirect_to @muscle
    else
      render :new
    end
  end

  def new
    @muscle = Muscle.new
  end  

  # UPDATE
  def edit
    @muscle = Muscle.find(params[:id])
  end

  def update
    @muscle = Muscle.find(params[:id])
    if @muscle.update_attributes(muscle_params)
      redirect_to @muscle
    else
      render :edit
    end
  end

  # DESTROY
  def destroy
    Muscle.find(params[:id]).destroy
    redirect_to muscles_path
  end

  private
    def muscle_params
      params.require(:muscle).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # CREATE
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to(root_path)
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  # UPDATE
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

    private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController\

  before_action :authenticate_user!, except: [:index, :show]

  # READ
  def index
    @workouts = Workout.where(user_id: nil).order(name: :asc).paginate(page: params[:page], :per_page => 10)
  end

  def show
    @workout = Workout.find(params[:id])
  end

  # CREATE
  def new
    @workout = Workout.new
    @workout.regiments.build
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render :new
    end
  end

  # UPDATE
  def edit
    @workout = Workout.find(params[:id])
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update_attributes(workout_params)
      redirect_to @workout
    else
      render :edit
    end
  end

  # DESTROY
  def destroy
    Workout.find(params[:id]).destroy
    redirect_to workouts_url
  end

  private
    def workout_params
      params.require(:workout).permit(:name, :exercise_id, regiments_attributes: [ :id, :exercise_id, :workout_id, :weight, :sets, :reps, :_destroy])
    end

  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom p-4 bg-dark">
    <div class="row text-center justify-content-between">
        
        <div class="col-md-2">
            <%= link_to "About", about_path, class:"text-capitalize font-weight-bold text-white curser" %>
        </div>
        <div class="col-md-2">
            <%= link_to "Exercises", exercises_path, class:"text-capitalize font-weight-bold text-white curser" %>
        </div>
        <div class="col-md-2">
            <%= link_to "Muscles", muscles_path, class:"text-capitalize font-weight-bold text-white curser" %>
        </div>
        <div class="col-md-2">
            <%= link_to "Workouts", workouts_path, class:"text-capitalize font-weight-bold text-white curser" %>
        </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-dark fixed-top px-5">
  <%= link_to ('<i class="fas fa-dumbbell text-warning fa-2x navbar-brand"> Kaizen Liftz</i>').html_safe, root_path %>
  <div class="ml-auto">
    <% if user_signed_in? %>
        <div class="btn-group">
            <div class="dropdown mr-4">
                <button class="btn btn-outline-light dropdown-toggle" type="button" data-toggle="dropdown">
                    My Account
                </button>
                <div class="dropdown-menu bg-light dropdown-menu-right text-right" >
                    <%= link_to "My Workouts", user_workouts_path(current_user), class:"text-dark text-capitalize d-block pr-4" %>
                    <%= link_to "My Settings", edit_user_registration_path, class:"text-dark text-capitalize d-block pr-4" %>
                </div>
            </div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"btn btn-outline-light text-capitalize" %>
        </div>
        
    <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-outline-light text-capitalize" %>
        <%= link_to "Sign In", new_user_session_path, class:"btn btn-outline-light text-capitalize" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaizenLiftz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
      integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
      crossorigin="anonymous"
    />
  </head>

  <body class="bg-secondary">
    <%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @profile.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@profile.errors.count, "error") %>.
        </div>
        <ul>
            <% @profile.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_paginate.html.erb
<%= will_paginate @profile, {:class => "text-primary text-center"}%>